name: 52pojie_sign

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  1 0 * * * 
  watch:
    types: started
  
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 签到       
      run: |
        cookie= ${{ secrets.COOKIE }}
        SCKEY=${{ secrets.SCKEY }}  
        
        cookie_list = ()
        IFS="#"
        
        for u in ${cookie[*]}
        do 
        cookie_list[${#cookie_list[*]}]=${u}
        done
        cookie_num=${#cookie_list[*]}
        
        for ((i=0;i<$cookie_num;i++))
        python 52pojie_sign.py <<EOF
        ${cookie_list[$i]}
        ${SCKEY}
        EOF
       
